services:
  postgres:
    image: postgres:13
    user: "999:999"
    environment:
      - POSTGRES_DB=apply
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'
  server:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=apply
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
      - POSTGRES_HOST=postgres
      - CONTENTFUL_BASE_URL=https://cdn.contentful.com/spaces
      - CONTENTFUL_SPACE_ID=9xs1613l9f7v
      - CONTENTFUL_ACCESS_TOKEN=I-ThsT55eE_B3sCUWEQyDT4VqVO3x__20ufuie9usns
      - CONTENTFUL_ENVIRONMENT=master
      - CONTENTFUL_CONTENT_TYPE=product
      - API_KEY=142caef0dd6c387225f6659c

    command: ["pnpm", "start"]